### ISSUE TITLE
getting this when running NPM Start

### ISSUE THREAD

**Issue by wsimon98** [onury5506/Discord-ChatGPT-Bot#19]
TypeError: Cannot read properties of null (reading 'split')
    at #seven (file:///mnt/dietpi_userdata/skynetimage/node_modules/aikey/index.js:120:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getAccessToken (file:///mnt/dietpi_userdata/skynetimage/chatgpt/access_token.js:6:15)
    at async initChatGPT (file:///mnt/dietpi_userdata/skynetimage/chatgpt/chatgpt.js:11:22)
    at async main (file:///mnt/dietpi_userdata/skynetimage/index.js:9:5)
root@DietPi:/mnt/dietpi_userdata/skynetimage/node_modules#

**Comment by wsimon98** [comment]
I really think this is a permissions issue though... Now that I'm digging into this. 

I checked and made sure everything has 0777.

**Comment by wsimon98** [comment]
just redid it all from step 1. works. my apologies.

**Comment by wsimon98** [comment]
resolved
