### ISSUE TITLE
Get terminated with ReferenceError: fetch is not defined

### ISSUE THREAD

**Issue by damoncoo** [onury5506/Discord-ChatGPT-Bot#25]
2023-04-01T17:17:53.392Z
Config saved!

```
ReferenceError: fetch is not defined
    at Moderations (file:///Users/xxx/Desktop/codes/Discord-ChatGPT-Bot/chatgpt/moderations.js:2:15)
    at askQuestion (file:///Users/xxx/Desktop/codes/Discord-ChatGPT-Bot/chatgpt/chatgpt.js:60:29)
    at handle_interaction_ask (file:///Users/xxx/Desktop/codes/Discord-ChatGPT-Bot/discord/discord_commands.js:89:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
file:///Users/xxx/Desktop/codes/Discord-ChatGPT-Bot/discord/discord_helpers.js:18
        .setDescription(response.slice(0, Math.min(response.length, 4096)))
                                 ^

TypeError: response.slice is not a function
    at createEmbedForAskCommand (file:///Users/xxx/Desktop/codes/Discord-ChatGPT-Bot/discord/discord_helpers.js:18:34)
    at generateInteractionReply (file:///Users/xxx/Desktop/codes/Discord-ChatGPT-Bot/discord/discord_helpers.js:122:23)
    at file:///Users/xxx/Desktop/codes/Discord-ChatGPT-Bot/discord/discord_commands.js:90:13
    at askQuestion (file:///Users/xxx/Desktop/codes/Discord-ChatGPT-Bot/chatgpt/chatgpt.js:67:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by onury5506** [comment]
You should use Nodejs V18+

**Comment by damoncoo** [comment]
> You should use Nodejs V18+

Just tried 18.15, same issue

**Comment by damoncoo** [comment]
I figured out why, using free plan, the API credit is run out
