### ISSUE TITLE
Error in the console

### ISSUE THREAD

**Issue by Manidarean5** [onury5506/Discord-ChatGPT-Bot#28]
TypeError: Cannot read properties of undefined (reading '0')
    at Moderations (file:///C:/Users/MACHENIKE/Documents/Discord-ChatGPT-Bot/chatgpt/moderations.js:12:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async askQuestion (file:///C:/Users/MACHENIKE/Documents/Discord-ChatGPT-Bot/chatgpt/chatgpt.js:60:23)

this is when I use /ask

**Comment by Manidarean5** [comment]
and I can´t sent messages in MD

**Comment by Manidarean5** [comment]
and i can't use /video

**Comment by Manidarean5** [comment]
Now the error is this:

TypeError: response.slice is not a function
    at createEmbedForAskCommand (file:///C:/Users/MACHENIKE/Documents/Discord-ChatGPT-Bot/discord/discord_helpers.js:18:34)
    at generateInteractionReply (file:///C:/Users/MACHENIKE/Documents/Discord-ChatGPT-Bot/discord/discord_helpers.js:122:23)
    at file:///C:/Users/MACHENIKE/Documents/Discord-ChatGPT-Bot/discord/discord_commands.js:103:13
    at askQuestion (file:///C:/Users/MACHENIKE/Documents/Discord-ChatGPT-Bot/chatgpt/chatgpt.js:67:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v19.0.0

**Comment by cangeloo** [comment]
> and I can´t sent messages in MD

you need message intent, enable that in the discord developer settings

**Comment by Manidarean5** [comment]
![image](https://github.com/onury5506/Discord-ChatGPT-Bot/assets/108998523/1124d7b5-de31-4410-b0c3-f9a2cfb03e17)

**Comment by Katanium** [comment]
Same issue here, message intent is on but still getting the same error

**Comment by onury5506** [comment]
The bug is fixed
