### ISSUE TITLE
Unable to use `/video`

### ISSUE THREAD

**Issue by FishyMine** [onury5506/Discord-ChatGPT-Bot#33]
Error.captureStackTrace(err, this);
          ^
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getProxies (file:///home/container/proxyService/freeProxyList.js:25:20)
    at async file:///home/container/proxyService/proxyService.js:7:32 {
  cause: [Error: C0B7F0DABE7F0000:error:0A00010B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:355:
  ] {
    library: 'SSL routines',
    reason: 'wrong version number',
    code: 'ERR_SSL_WRONG_VERSION_NUMBER'
  }

**Comment by onury5506** [comment]
The command removed
