### ISSUE TITLE
Terminal Error

### ISSUE THREAD

**Issue by Pallettb** [onury5506/Discord-ChatGPT-Bot#35]
does this bot still work? I'm getting terminal errors when writing a command

**Comment by Pallettb** [comment]
This is the error
     
      at Moderations (file:///root/Discord-ChatGPT-Bot/chatgpt/moderations.js:12:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async askQuestion (file:///root/Discord-ChatGPT-Bot/chatgpt/chatgpt.js:60:23)
file:///root/Discord-ChatGPT-Bot/discord/discord_helpers.js:18
        .setDescription(response.slice(0, Math.min(response.length, 4096)))
                                 ^

TypeError: response.slice is not a function
    at createEmbedForAskCommand (file:///root/Discord-ChatGPT-Bot/discord/discord_helpers.js:18:34)
    at generateInteractionReply (file:///root/Discord-ChatGPT-Bot/discord/discord_helpers.js:122:23)
    at file:///root/Discord-ChatGPT-Bot/discord/discord_commands.js:90:13
    at askQuestion (file:///root/Discord-ChatGPT-Bot/chatgpt/chatgpt.js:67:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.16.0
